### ISSUE TITLE
kube-ps1 on windows

### ISSUE THREAD

**Issue by gerardgorrion** [jonmosco/kube-ps1#141]
Hi all. 

There're some plan to do version to windows systems OS?

Thanks and good job.

**Comment by thomasliddledba** [comment]
Hi @gerardgorrion, this is a great idea and something I've proposed in passing to @jonmosco.  In a conversation with @jonmosco, I've decided to look into this and port `kube-ps1` code to PowerShell in a new repo.  I did something similar with `kubectx` and `kubens` by creating [kubectxwin](https://github.com/thomasliddledba/kubectxwin) and [kubectxns](https://github.com/thomasliddledba/kubenswin).

@jonmosco will be a reviewer for me.

I'll assign this to myself and start working on something over the next few weeks.  Once I have a repo created, I'll close out this issue and updated it with the new location.

Thanks and great suggestion.

**Comment by rr-todd-murchison** [comment]
I guess this never happened?

**Comment by dooblem** [comment]
In case you want to use Bash with Cygwin : https://github.com/jonmosco/kube-ps1/pull/186

**Comment by thomasliddledba** [comment]
After some consideration and discussions with other users, I've decided not to create the proposed feature due to the lack of interest. Users that I've talked to and engaged with our Linux users and the few Windows users that I do talk with use the Windows Linux Subsystem or the use case pointed out by @dooblem.

If you believe in the value of this feature, please give a thumbs up to the previous comment I made on this issue. This will help us gauge the community's interest more accurately and reconsider its implementation.

**Comment by jonmosco** [comment]
Closing due to lack of interest.
